CREATE TABLE accounts (
    account_id UUID PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE balances (
    account_id UUID NOT NULL,
    asset VARCHAR(32) NOT NULL,
    available BIGINT NOT NULL,
    held BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (account_id, asset),
    CONSTRAINT fk_balances_account
        FOREIGN KEY (account_id) REFERENCES accounts (account_id)
);

CREATE TABLE orders (
    order_id UUID PRIMARY KEY,
    account_id UUID NOT NULL,
    client_order_id VARCHAR(64) NOT NULL,
    symbol VARCHAR(32) NOT NULL,
    side VARCHAR(8) NOT NULL,
    order_type VARCHAR(16) NOT NULL,
    tif VARCHAR(8) NOT NULL,
    status VARCHAR(32) NOT NULL,
    price BIGINT,
    quantity BIGINT,
    remaining_qty BIGINT NOT NULL,
    quote_qty BIGINT,
    cum_base_qty BIGINT NOT NULL DEFAULT 0,
    cum_quote_qty BIGINT NOT NULL DEFAULT 0,
    accepted_seq BIGINT,
    ordered_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_orders_account
        FOREIGN KEY (account_id) REFERENCES accounts (account_id),
    CONSTRAINT uq_orders_account_client_order_id
        UNIQUE (account_id, client_order_id)
);

CREATE TABLE trades (
    trade_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol VARCHAR(32) NOT NULL,
    price BIGINT NOT NULL,
    quantity BIGINT NOT NULL,
    buy_order_id UUID NOT NULL,
    sell_order_id UUID NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_trades_buy_order
        FOREIGN KEY (buy_order_id) REFERENCES orders (order_id),
    CONSTRAINT fk_trades_sell_order
        FOREIGN KEY (sell_order_id) REFERENCES orders (order_id)
);

CREATE TABLE idempotency_keys (
    account_id UUID NOT NULL,
    client_order_id VARCHAR(64) NOT NULL,
    order_id UUID NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (account_id, client_order_id),
    CONSTRAINT fk_idempotency_account
        FOREIGN KEY (account_id) REFERENCES accounts (account_id),
    CONSTRAINT fk_idempotency_order
        FOREIGN KEY (order_id) REFERENCES orders (order_id)
);
